Mention minimum Ember version
typed-ember/glint pull request #388
Opened 2022-08-22 11:57 UTC by machty

I believe it's Ember 4, but if it's not I can change it, just so long as it's mentioned somewhere.

2022-08-22 13:16 UTC, kpfefferle commented
Hmm, we're definitely using Glint with 3.28... 🤔

2022-08-22 13:52 UTC, machty commented
@kpfefferle I updated it to mention 3.24 as the minimum version after I confirmed with some testing of my own.

2022-08-23 00:19 UTC, chriskrycho requested changes
Thanks! Our projects (not just Typed Ember but Ember) generally use `v` instead of `Version`, so I suggested that change. Once that's done, we'll merge it.

2022-08-23 00:19 UTC, chriskrycho commented on README.md
> +[Glint] is a set of tools to aid in developing code that uses the Glimmer VM for rendering, such as [Ember.js] (Version 3.24+) and [GlimmerX] projects. Similar to [Vetur] for Vue projects or [Svelte
```suggestion
[Glint] is a set of tools to aid in developing code that uses the Glimmer VM for rendering, such as [Ember.js] v3.24+ and [GlimmerX] projects. Similar to [Vetur] for Vue projects or [Svelte Language Tools], Glint consists of a CLI and a language server to provide feedback and enforce correctness both locally during editing and project-wide in CI.
```

2022-08-23 00:19 UTC, chriskrycho commented on docs/ember/installation.md
> +To use Glint with [Ember](https://github.com/emberjs/ember.js) (Version 3.24 or higher), you'll add the `@glint/core` and `@glint/environment-ember-loose` packages to your project's `devDependencies`
```suggestion
To use Glint with [Ember](https://github.com/emberjs/ember.js) v3.24 or higher, you'll add the `@glint/core` and `@glint/environment-ember-loose` packages to your project's `devDependencies`, then add a `"glint"` key to your project's `tsconfig.json`.
```

2022-08-23 00:19 UTC, chriskrycho commented on docs/overview.md
> +Glint is a set of tools to aid in developing code that uses the Glimmer VM for rendering, such as [Ember.js] (Version 3.24+) and [GlimmerX] projects. Similar to [Vetur] for Vue projects or [Svelte La
```suggestion
Glint is a set of tools to aid in developing code that uses the Glimmer VM for rendering, such as [Ember.js] v3.24+ and [GlimmerX] projects. Similar to [Vetur] for Vue projects or [Svelte Language Tools], Glint consists of a CLI and a language server to provide feedback and enforce correctness both locally during editing and project-wide in CI.
```

2022-08-23 00:27 UTC, machty commented
@chriskrycho accepted your changes

2022-08-23 00:29 UTC, chriskrycho approved these changes

2022-08-23 03:13 UTC, merged

2022-08-23 03:13 UTC, chriskrycho commented
Windows failure is spurious. Another timeout issue, @dfreeman.